Repository corbin-hayden13/raspberrypi_cs370, pull requests merged in 2023-04, with the labels that each got.

#2 Create HMR_CS370_Report_Outline
  HMR_CS370_Report_Outline
Labels: documentation

#9 7 get rgb values of most common colors
  DisplayGUI.py
  RealtimeVideo.py
Labels: enhancement

#21 20 alternate UI design
  ColorEditor.py
  ColorUIElement.py
  DisplayGUI.py
  RealtimeVideo.py
Labels: documentation

#28 corbin-hayden13 fix masking
  ColorEditor.py
  ColorUIElement.py
  DisplayGUI.py
  tables/tk-colours.xlsx
Labels: bug

#25 24 add to report
  HMR Term Project Report.docx
  HMR_CS370_Report_Outline
Labels: documentation

#27 26 cite code
  DisplayGUI.py
  RealtimeVideo.py
Labels: documentation

#29 Refresh button works!
  DisplayGUI.py
  EventHandler.py
  RealtimeVideo.py
Labels: enhancement
